name: LayerZeroVyper
dependencies:
  - name: SolidityExamples
    github: LayerZero-Labs/solidity-examples
    branch: main
    contracts_folder: contracts

solidity:
  import_remapping:
    - "@layerzero=SolidityExamples/main"
